# Chapter 2

In [ ]:
# Run without any intallation needed
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import tensorflow as tf


In [ ]:
# The preinstalled version is Tensorflow version 2 (with earger execution activated)
tf.__version__

'2.17.0'

In [ ]:
# How to import Keras
from tensorflow import keras

In [ ]:
import cv2
import matplotlib.pyplot as plt
test_img = cv2.imread("/content/ADE_train_00000192.jpg")
imgplot = plt.imshow(test_img)

In [ ]:
import cv2
import matplotlib.pyplot as plt

test_img = cv2.imread("/content/ADE_train_00000192.jpg")
test_img = cv2.cvtColor(test_img, cv2.COLOR_BGR2RGB)
imgplot = plt.imshow(test_img)


In [ ]:
import cv2
import matplotlib.pyplot as plt

test_img = cv2.imread("/content/ADE_train_00000192.jpg")
print(test_img.shape)

test_img = cv2.cvtColor(test_img, cv2.COLOR_BGR2GRAY)
print(test_img.shape)


(1800, 2878, 3)
(1800, 2878)


In [ ]:
import cv2
import matplotlib.pyplot as plt

test_img = cv2.imread("/content/ADE_train_00000192.jpg")
print(test_img.shape)

test_img = cv2.cvtColor(test_img, cv2.COLOR_BGR2GRAY)
print(test_img.shape)
plt.imshow(test_img, cmap='gray')


In [ ]:
import cv2
import matplotlib.pyplot as plt

test_img = cv2.imread("/content/ADE_train_00000192.jpg")
test_img = cv2.cvtColor(test_img, cv2.COLOR_BGR2GRAY)

cv2.imwrite("/content/gray_ADE_train_00000192.jpg", test_img)


True

In [ ]:
import numpy as np
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
import cv2
import matplotlib.pyplot as plt

test_img = cv2.imread("/content/ADE_train_00000192.jpg")
print("Type of the test_img variable is: ", type(test_img))
print("Shape of the test_img array before conversion is: ", test_img.shape)

# We keep only the third channel
test_img = test_img[:,:,2]
print("Shape of the test_img array after conversion is: ", test_img.shape)

# We save the converted image
cv2.imwrite("/content/numpy_gray_ADE_train_00000192.jpg", test_img)

# We display the image
plt.imshow(test_img, cmap="gray")


In [ ]:
from PIL import Image
import matplotlib.pyplot as plt

# Load the image with the PIL librarulibrary
test_img = Image.open("/content/ADE_train_00000192.jpg")

# When loaded with PIL, the output is not an ndarray but a PIL object
print(type(test_img))

# Convert to grayscale
test_img = test_img.convert('L')

# Display the image
plt.imshow(test_img, cmap="gray")

# Save the image with PIL library
test_img.save("/content/numpy_gray_ADE_train_00000192.jpg")


In [ ]:
import cv2
import matplotlib.pyplot as plt

test_img = cv2.imread("/content/ADE_train_00000192.jpg")
print("Type of the test_img variable is: ", type(test_img))
print("Shape of the test_img array before conversion is: ", test_img.shape)

# We keep only the third channel
test_img = test_img[:,:,2]
print("Shape of the test_img array after conversion is: ", test_img.shape)

# We display the image
plt.imshow(test_img, cmap="gray")

# We save the converted image
cv2.imwrite("/content/numpy_gray_ADE_train_00000192.jpg", test_img)


In [ ]:

import tensorflow as tf

x = tf.constant(8, name="x_const")
y = tf.constant(5, name="y_const")
sum = tf.add(x, y, name="x_y_sum")
print(sum)
print("we can extract  the numpy array from this tensor: ", sum.numpy())


tf.Tensor(13, shape=(), dtype=int32)
we can extract  the numpy array from this tensor:  13


In [ ]:
dims = (3, 5, 2)
value_1 = 2.0
value_2 = 5.0
x = tf.fill(dims, value_1)
y = tf.fill(dims, value_2)
z = tf.multiply(x, y)
print(z)


tf.Tensor(
[[[10. 10.]
  [10. 10.]
  [10. 10.]
  [10. 10.]
  [10. 10.]]

 [[10. 10.]
  [10. 10.]
  [10. 10.]
  [10. 10.]
  [10. 10.]]

 [[10. 10.]
  [10. 10.]
  [10. 10.]
  [10. 10.]
  [10. 10.]]], shape=(3, 5, 2), dtype=float32)


In [ ]:
x = tf.constant([[2, 3],
                [10, 4]], dtype=tf.float32)
y = tf.constant([[2, 1],
                [1, 2]], dtype=tf.float32)
dot_product = tf.matmul(x, y)
print(dot_product)
dot_product.shape

tf.Tensor(
[[ 7.  8.]
 [24. 18.]], shape=(2, 2), dtype=float32)


TensorShape([2, 2])

In [ ]:
tf.reshape(dot_product, [4,1])

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[ 7.],
       [ 8.],
       [24.],
       [18.]], dtype=float32)>

In [ ]:
tf.reshape(dot_product, [-1,1])

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[ 7.],
       [ 8.],
       [24.],
       [18.]], dtype=float32)>

In [ ]:
tf.reduce_mean(dot_product)

<tf.Tensor: shape=(), dtype=float32, numpy=14.25>

In [ ]:
x = tf.Variable([1, 2], dtype=tf.float32)
x.assign([3, 4])
print(x)
x.assign_add([1,1])
print(x)



<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([3., 4.], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([4., 5.], dtype=float32)>


In [ ]:
# Let's assume that we have an input of shape (784,1) and that we have labels of shape (10,1)
n_hidden_1 = 256
n_hidden_2 = 128
n_hidden_3 = 64
n_input = 784
n_classes  = 10
stddev = 0.1

class MyModel(tf.Module):
 def __init__(self, **kwargs):
   super().__init__(**kwargs)

   # Initialize the weights and biases in a random way
   self.weights = {
       'h1': tf.Variable(tf.random.normal([n_input, n_hidden_1], 				stddev=stddev)),
       'h2': tf.Variable(tf.random.normal([n_hidden_1, n_hidden_2], 				stddev=stddev)),
       'h3': tf.Variable(tf.random.normal([n_hidden_2, n_hidden_3], 				stddev=stddev)),
       'out': tf.Variable(tf.random.normal([n_hidden_3, n_classes], 				stddev=stddev))
   }
   self.biases = {
       'b1': tf.Variable(tf.random.normal([n_hidden_1])),
       'b2': tf.Variable(tf.random.normal([n_hidden_2])),
       'b3': tf.Variable(tf.random.normal([n_hidden_3])),
       'out': tf.Variable(tf.random.normal([n_classes]))
   }

 def __call__(self, x):
   layer_1 = tf.nn.sigmoid(tf.add(tf.matmul(x, self.weights['h1']), self.biases['b1']))
   layer_2 = tf.nn.sigmoid(tf.add(tf.matmul(layer_1, self.weights['h2']), self.biases['b2']))
   layer_3 = tf.nn.sigmoid(tf.add(tf.matmul(layer_2, self.weights['h3']), self.biases['b3']))
   return (tf.matmul(layer_3, self.weights['out']) + self.biases['out'])

model = MyModel()


In [ ]:
hidden_1_size = 256
hidden_2_size = 128
hidden_3_size = 64
input_size = 784
n_classes  = 10
model = tf.keras.Sequential()

model.add(tf.keras.layers.Dense(hidden_1_size,activation = 'sigmoid',input_shape=(input_size,)))
model.add(tf.keras.layers.Dense(hidden_2_size,activation = 'sigmoid'))
model.add(tf.keras.layers.Dense(hidden_3_size,activation = 'sigmoid'))
model.add(tf.keras.layers.Dense(n_classes))
